apiVersion: v1alpha1
kind: AnnotationSetting
metadata:
  generateName: annotation-setting-
spec:
  targetRef:
    group: content.halo.run
    kind: Post
  formSchema:
    - $formkit: "select"
      name: "enable_aside"
      label: "是否啟用側邊欄"
      value: "true"
      options:
        - value: "true"
          label: 是
        - value: "false"
          label: 否
    - $formkit: "select"
      name: "enable_page_meta"
      label: "是否展示頁面元資訊（即頂部的字數、閱讀量等資料）"
      value: "true"
      options:
        - value: "true"
          label: 是
        - value: "false"
          label: 否
    - $formkit: "select"
      name: "enable_passage_tips"
      label: "是否展示溫馨提示"
      value: "true"
      options:
        - value: "true"
          label: 是
        - value: "false"
          label: 否
    - $formkit: "select"
      name: "enable_collect_check"
      label: "是否啟用百度收錄檢查"
      value: "true"
      options:
        - value: "true"
          label: 是
        - value: "false"
          label: 否
    - $formkit: "select"
      name: "enable_read_limit"
      label: "是否開啟評論後可見"
      value: "false"
      options:
        - value: "true"
          label: 是
        - value: "false"
          label: 否
    - $formkit: "select"
      name: "use_raw_content"
      label: "是否渲染原始內容"
      value: "false"
      options:
        - value: "true"
          label: 是
        - value: "false"
          label: 否
    - $formkit: "select"
      name: "enable_comment"
      label: "是否啟用評論功能"
      value: "true"
      options:
        - value: "true"
          label: 是
        - value: "false"
          label: 否
    - $formkit: "select"
      name: "enable_toc"
      label: "是否啟用 Toc 目錄"
      value: "true"
      options:
        - value: "true"
          label: 是
        - value: "false"
          label: 否
    - $formkit: "text"
      name: "toc_depth"
      label: "Toc 目錄預設展開層級 0~6，對應標題層級 h1 ～ h6"
      value: "0"
    - $formkit: "text"
      name: "img_max_width"
      label: "圖片最大寬度"
      value: "100%"
    - $formkit: "select"
      name: "img_align"
      label: "圖片對齊方式"
      value: "center"
      options:
        - value: "center"
          label: 居中
        - value: "left"
          label: 左對齊
        - value: "right"
          label: 右對齊
    - $formkit: "select"
      name: "enable_copy"
      label: "是否允許複製內容"
      value: "true"
      options:
        - value: "true"
          label: 是
        - value: "false"
          label: 否
    - $formkit: "select"
      name: "enable_donate"
      label: "是否啟用打賞（必須配置好相應二維碼）"
      value: "true"
      options:
        - value: "true"
          label: 是
        - value: "false"
          label: 否
    - $formkit: "select"
      name: "enable_share"
      label: "是否啟用分享"
      value: "true"
      options:
        - value: "true"
          label: 是
        - value: "false"
          label: 否
    - $formkit: "select"
      name: "enable_like"
      label: "是否啟用點贊"
      value: "true"
      options:
        - value: "true"
          label: 是
        - value: "false"
          label: 否
    - $formkit: "select"
      name: "enable_fold_long_code"
      label: "是否開啟長程式碼塊自動摺疊"
      value: "true"
      options:
        - value: "true"
          label: 是
        - value: "false"
          label: 否

---

apiVersion: v1alpha1
kind: AnnotationSetting
metadata:
  generateName: annotation-setting-
spec:
  targetRef:
    group: ""
    kind: MenuItem
  formSchema:
    - $formkit: "text"
      name: "icon"
      label: "圖示"

---

apiVersion: v1alpha1
kind: AnnotationSetting
metadata:
  generateName: annotation-setting-
spec:
  targetRef:
    group: content.halo.run
    kind: SinglePage
  formSchema:
    - $formkit: "select"
      name: "enable_aside"
      label: "是否啟用側邊欄"
      value: "true"
      options:
        - value: "true"
          label: 是
        - value: "false"
          label: 否
    - $formkit: "select"
      name: "enable_page_meta"
      label: "是否展示頁面元資訊（即頂部的字數、閱讀量等資料）"
      value: "true"
      options:
        - value: "true"
          label: 是
        - value: "false"
          label: 否
    - $formkit: "select"
      name: "enable_passage_tips"
      label: "是否展示溫馨提示"
      value: "true"
      options:
        - value: "true"
          label: 是
        - value: "false"
          label: 否
    - $formkit: "select"
      name: "enable_collect_check"
      label: "是否啟用百度收錄檢查"
      value: "true"
      options:
        - value: "true"
          label: 是
        - value: "false"
          label: 否
    - $formkit: "select"
      name: "enable_read_limit"
      label: "是否開啟評論後可見"
      value: "false"
      options:
        - value: "true"
          label: 是
        - value: "false"
          label: 否
    - $formkit: "select"
      name: "use_raw_content"
      label: "是否渲染原始內容"
      value: "false"
      options:
        - value: "true"
          label: 是
        - value: "false"
          label: 否
    - $formkit: "select"
      name: "enable_comment"
      label: "是否啟用評論功能"
      value: "true"
      options:
        - value: "true"
          label: 是
        - value: "false"
          label: 否
    - $formkit: "select"
      name: "enable_toc"
      label: "是否啟用 Toc 目錄"
      value: "true"
      options:
        - value: "true"
          label: 是
        - value: "false"
          label: 否
    - $formkit: "text"
      name: "toc_depth"
      label: "Toc 目錄預設展開層級 0~6，對應標題層級 h1 ～ h6"
      value: "0"
    - $formkit: "text"
      name: "img_max_width"
      label: "圖片最大寬度"
      value: "100%"
    - $formkit: "select"
      name: "img_align"
      label: "圖片對齊方式"
      value: "center"
      options:
        - value: "center"
          label: 居中
        - value: "left"
          label: 左對齊
        - value: "right"
          label: 右對齊
    - $formkit: "select"
      name: "enable_copy"
      label: "是否允許複製內容"
      value: "true"
      options:
        - value: "true"
          label: 是
        - value: "false"
          label: 否
    - $formkit: "select"
      name: "enable_share"
      label: "是否啟用分享"
      value: "true"
      options:
        - value: "true"
          label: 是
        - value: "false"
          label: 否
    - $formkit: "select"
      name: "enable_like"
      label: "是否啟用點贊"
      value: "true"
      options:
        - value: "true"
          label: 是
        - value: "false"
          label: 否
    - $formkit: "select"
      name: "enable_fold_long_code"
      label: "是否開啟長程式碼塊自動摺疊"
      value: "true"
      options:
        - value: "true"
          label: 是
        - value: "false"
          label: 否